# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Aurelia CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Install Dependencies
      run: |
        cd test-app
        npm ci --prefer-offline
    - name: lint check
      run: |
        cd test-app
        npm run lint
    - name: Build Angular
      run: |
        cd test-app
        npm run build
